### ISSUE TITLE
Comprehesive list of env_vars values

### ISSUE THREAD

**Issue by wilson-walrus** [redhat-cop/agnosticd#1045]
**Is your feature request related to a problem? Please describe.**

When modifying current configs or creating new ones I would like to know my options for setting env_vars. There is a good example of this in the [satellite-vm](https://github.com/redhat-cop/agnosticd/tree/development/ansible/configs/satellite-vm) config.

**Describe the solution you'd like**

An Ideal solution would be a table like the one referenced above that provides possible variables to set when configuring systems. My team would be interested in setting: cpu, memory, storage, and network configurations. I have seen multiple examples of this already written in some configs, but it would be nice if they were all in a central location.

**Describe alternatives you've considered**

An alternative could be a sample vars file that includes similar information. I am happy to discuss or consider any alternatives this issue provokes.

**Comment by fridim** [comment]
Hi,
Thanks for bringing that up.

Common variables could be gathered in a central location, but anything config-related, should definitely be documented in the config readme or `default_vars.yml` or `sample_vars*.yml` of that config.

Configs are usually owned by the config owner(s), so unless we open one issue per config to fix the problem of undocumented vars, i don't see how this could be resolved.

Can we change this issue to address only the variables common to all configs ? In other words, variables of agnosticd core, like `cloud_provider`, `env_type` ?

**Comment by fridim** [comment]
core variables are now defined in https://github.com/redhat-cop/agnosticd/blob/development/docs/Variables.adoc

Regarding roles variables here are the rules extracted from: https://github.com/redhat-cop/agnosticd/blob/development/docs/Contributing.adoc:

Roles must have documented variables. This can be documented in either:
- Role defaults/main.yml (preferred)
- Role README file
Choose one or the other. If you are commenting your variables in the defaults, your README should just point to this file. Do not split your variable documentation across these.

For configs, it currently lives in `default_vars*.yml` in the config.
