### ISSUE TITLE
Migration workloads do not work in Python 3 virtualenv on EL7 because of missing selinux module.

### ISSUE THREAD

**Issue by jmontleon** [redhat-cop/agnosticd#1080]
**Describe the bug**
In response to the python3 virtualenv created on an EL7 host in this PR
https://github.com/redhat-cop/agnosticd/pull/1072

We are seeing selinux errors:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Failed to detect selinux python bindings at ['/usr/local/lib64/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']
fatal: [clientvm.pranav.internal]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ec2-52-2-178-104.compute-1.amazonaws.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1580419137.6182914-72122596545255/AnsiballZ_k8s.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1580419137.6182914-72122596545255/AnsiballZ_k8s.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1580419137.6182914-72122596545255/AnsiballZ_k8s.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 656, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 626, in _load_backward_compatible\r\n  File \"/tmp/ansible_k8s_payload_p5zsqpqk/ansible_k8s_payload.zip/ansible/module_utils/basic.py\", line 74, in <module>\r\n  File \"/opt/virtualenvs/k8s/lib/python3.6/site-packages/selinux/__init__.py\", line 104, in <module>\r\n    check_system_sitepackages()\r\n  File \"/opt/virtualenvs/k8s/lib/python3.6/site-packages/selinux/__init__.py\", line 101, in check_system_sitepackages\r\n    \"Failed to detect selinux python bindings at %s\" % system_sitepackages\r\nException: Failed to detect selinux python bindings at ['/usr/local/lib64/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**To Reproduce**
Attempt to deploy the ocp4 migration workload.

**Expected behavior**
The workload succeeds

**Additional context**
This module is only a shim:
https://github.com/redhat-cop/agnosticd/pull/1072/files#diff-d1aef42e8197daf5bf7a5fdd3431c7c1R37

https://github.com/pycontribs/selinux/blob/master/README.rst
09
"You still need to have libselinux python bindings package installed on your system for it to work but you no longer have the problem of not being able to import it from inside isolated (default) virtualenvs."

The real python3 libselinux module needs to be installed, which does not exist on RHEL 7
https://bugzilla.redhat.com/show_bug.cgi?id=1719978#c33

**Comment by jwmatthews** [comment]
cc @wkulhanek

**Comment by wkulhanek** [comment]
Set install_ftl: true as a workaround. 

--
Wolfgang

**Comment by jmontleon** [comment]
Does this do anything besides install the same shim package that's already installed in the virtualenv? All I see is https://github.com/redhat-cop/agnosticd/blob/e8f00002274eaec9ab06e6600735890b72fad15e/ansible/roles/bastion-lite/tasks/main.yml#L48-L65

**Comment by jmontleon** [comment]
Re: https://github.com/redhat-cop/agnosticd/commit/8bcffe3067e9e30a269366c722602239c6bdd702

Adding the libselinux shim isn't going to fix this. It's just a shim and already installed in the virtualenv 
https://github.com/redhat-cop/agnosticd/pull/1072/files#diff-d1aef42e8197daf5bf7a5fdd3431c7c1R37

As I mentioned in my comment there is no libselinux package for python3 on EL7 https://bugzilla.redhat.com/show_bug.cgi?id=1719978#c33

Thus: `Failed to detect selinux python bindings at ['/usr/local/lib64/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']`

**Comment by wkulhanek** [comment]
I pushed a fix. The Selinux package needs to be installed on the system. Not the virtualenv. 

--
Wolfgang
