### ISSUE TITLE
Add Quota example to ocp-workload-example

### ISSUE THREAD

**Issue by newgoliath** [redhat-cop/agnosticd#1869]
**Is your feature request related to a problem? Please describe.**
Typical user will need to add quotas, too.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wkulhanek** [comment]
Or we could just point to the shared cluster workload...

**Comment by newgoliath** [comment]
Good point.  I'll also add AuthN workload usage.

WK wrote a bunch of base workloads that workload devs are encouraged to use.

All part of spiffing up the example for the AgonsticD trainign.

@NonyNo3lle
