### ISSUE TITLE
RHACM workload will not deploy in 4.4.8/.9

### ISSUE THREAD

**Issue by stencell** [redhat-cop/agnosticd#2093]
**Describe the bug**
RHACM cannot deploy due to [BZ1847540](https://bugzilla.redhat.com/show_bug.cgi?id=1847540). There is a workaround noted [here](https://bugzilla.redhat.com/show_bug.cgi?id=1839909#c5).

Can you please add some task(s) to workaround this until a fix is backported to 4.4.x?

@mvazquezc

**Comment by wkulhanek** [comment]
Thanks for the fix @mvazquezc . Verified it works.
