### ISSUE TITLE
Wrong Issue, please delete

### ISSUE THREAD

**Issue by gmontalvoy** [redhat-cop/agnosticd#354]
**Please delete**

My fault, sorry.

**Comment by fridim** [comment]
what was the issue ?

Can we prevent it with a better error message ?

**Comment by gmontalvoy** [comment]
If you only want to deploy just three masters (just an example), so you set the *_count variables to 0, but this will cause to DependsON will be empty and that cannot be validated against Cloudformation.

You're right, we could provide a better error message but in a second though,maybe the ocp-workshop was not planned to be used like that.

I am currently testing the three-tier-app to try to get three-masters deployment done but if it isn't work I would suggest to provide another new config.

Let's see a very simple use case:
In a BZ like this https://bugzilla.redhat.com/show_bug.cgi?id=1642589 sometimes you only need the mininum to perform a deployment, not for an app, not for a workshop just to test if the latest changes worked or not. From my perspective I have a lot of that kind of BZ that needs to be tested in an agile way
