### ISSUE TITLE
in OCP4 configs, automatically grab the openshift_install.log

### ISSUE THREAD

**Issue by fridim** [redhat-cop/agnosticd#511]
**Is your feature request related to a problem? Please describe.**
As a developer, i need access to the logs when deployment or deletion fails.

**Describe the solution you'd like**
After openshift-install commands, grab the .openshift_install.log file, gzip it, and copy it to `{{ output_dir }}`.

**Describe alternatives you've considered**
Today, developer needs to SSH to the clientvm to tail or cat the log. => tedious.

**Additional context**
configs:
- ocp4-workshop
- ocp4-shared

**Comment by gmontalvoy** [comment]
Should be also applied to the other ocp4 configs?  (disconnected, cluster, ha.....)

**Comment by fridim** [comment]
If we can, but some are labs, and usually openshift is installed by the student

Those i'm certain:

- ocp4-cluster
- ocp4-workshop
