### ISSUE TITLE
You must specify an allocation id when mapping an address to a VPC instance

### ISSUE THREAD

**Issue by hupiper** [redhat-cop/agnosticd#574]
**Describe the bug**
I'm running both the mig-agnostic/3.x and mig-agnostic/4.x create workshop scripts that call agnosticd to create clusters for testing the ocp migration tool. When trying to create either cluster, I get this error in the infra-ec2-template-create : Launch CloudFormation template (local) step:

"AWS::EC2::EIP clientvm1EIP CREATE_FAILED: You must specify an allocation id when mapping an address to a VPC instance (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: afaab81c-a654-40fe-bea3-0ac9bd893dd5)"

**To Reproduce**
Steps to reproduce the behavior, ex:
1. Follow prereqs on https://github.com/fusor/mig-agnosticd
2. Follow pre-provisioning steps at https://github.com/fusor/mig-agnosticd
3. Run https://github.com/fusor/mig-agnosticd/tree/master/4.x/create_ocp4_workshop.sh or https://github.com/fusor/mig-agnosticd/tree/master/4.x/create_ocp4_workshop.sh
4. TASK [infra-ec2-template-create : Launch CloudFormation template (local)] ******
Tuesday 13 August 2019  09:24:31 -0500 (0:00:00.053)       0:00:09.059 ******** 
 [WARNING]: Using a variable for a task's 'args' is unsafe in some situations
(see https://docs.ansible.com/ansible/devel/reference_appendices/faq.html
#argsplat-unsafe)

fatal: [localhost]: FAILED! => {"attempts": 1, "changed": true, "events": ["StackEvent AWS::CloudFormation::Stack ocp4-workshop-mad0805ocp4b CREATE_FAILED", "StackEvent AWS::Route53::RecordSetGroup DnsPublicDelegation CREATE_FAILED", "StackEvent AWS::Route53::RecordSetGroup clientvm1InternalDns CREATE_FAILED", "StackEvent AWS::EC2::EIP clientvm1EIP CREATE_FAILED", "StackEvent AWS::Route53::RecordSetGroup clientvm1InternalDns CREATE_IN_PROGRESS", "StackEvent AWS::Route53::RecordSetGroup clientvm1InternalDns CREATE_IN_PROGRESS", "StackEvent AWS::Route53::HostedZone DnsZonePrivate CREATE_COMPLETE", "StackEvent AWS::EC2::EIP clientvm1EIP CREATE_IN_PROGRESS", "StackEvent AWS::EC2::EIP clientvm1EIP CREATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance clientvm1 CREATE_COMPLETE"...

**Expected behavior**
I expect the cloudformation stack to complete correctly and build the cluster for me. 

**Screenshots / logs**
If applicable, add logs to help explain your problem.

**Verions (please complete the following information):**
 - OS
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.6 (Maipo)"
 - AAD version (`git log --pretty=oneline -2`)
9a1dac083638b590aacf747d890756b2b0ee451b Started the updates to the ansible-tower config readme
b7f05e10d5d507b3c6ad6b420245d7ae7223431e Updated env_type in new ansible-tower config
 - Ansible (`ansible --version`)
ansible 2.8.2
 - cloud provider CLI (aws-cli,  azure, ..)
aws-cli/1.16.211 Python/2.7.5 Linux/3.10.0-957.21.3.el7.x86_64 botocore/1.12.201

**Additional context**
![Screenshot from 2019-08-13 13-15-51](https://user-images.githubusercontent.com/1512878/62966407-94446880-bdcc-11e9-9458-e559c4e57dbc.png)

**Comment by jwmatthews** [comment]
@wkulhanek @NonyNo3lle any tips for how we can help @hupiper debug this.  

Assuming issue may be related to @hupiper AWS account as we've run similar configurations in other AWS accounts without seeing this issue before.

**Comment by hupiper** [comment]
I was able to get an AWS cluster up using my account this morning (4.19). It looks like I have to limit the zones I can use in the region I chose.

**Comment by jimbarlow** [comment]
I'm having the same problem as @hupiper.   The cloudformations template is spinning up Elastic IPs, and the node instances with public IPs.   The template is not able to apply the Elastic IPs to the instances, so they stay with the non-elastic public ips until the template fails with "You must specify an allocation id when mapping an address to a VPC instance"
This is a personal paid account for AWS, and I am working in us-east-1 with domain names (zones) hosted in the same region via Route 53.    Any insight into what might be "wrong" with my account?
