### ISSUE TITLE
Code Ready Workspaces doesn't deploy against OCP4

### ISSUE THREAD

**Issue by steven-ellis** [redhat-cop/agnosticd#600]
**Describe the bug**
Workload ocp-workload-codeready-workspaces won't deploy against OCP4 Workshop

**To Reproduce**
Steps to reproduce the behavior, ex:
1. Deploy a standard OCP4 workshop
2. Run CRW deployment from ocp-workload-codeready-workspaces
3. Issues due to ocadm command
4. Issues due to missing group OPENTLC-PROJECT-PROVISIONERS

**Expected behavior**

**Screenshots / logs**
```
failed: [bastion.akl-ceba.sandbox302.opentlc.com] (item=OPENTLC-PROJECT-PROVISIONERS) => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "ansible_loop_var": "item", "changed": true, "cmd": "oc adm groups add-users OPENTLC-PROJECT-PROVISIONERS codeready-user", "delta": "0:00:00.246669", "end": "2019-08-19 00:28:56.047875", "item": "OPENTLC-PROJECT-PROVISIONERS", "msg": "non-zero return code", "rc": 1, "start": "2019-08-19 00:28:55.801206", "stderr": "Error from server (NotFound): groups.user.openshift.io \"OPENTLC-PROJECT-PROVISIONERS\" not found", "stderr_lines": ["Error from server (NotFound): groups.user.openshift.io \"OPENTLC-PROJECT-PROVISIONERS\" not found"], "stdout": "", "stdout_lines": []}
````

**Verions (please complete the following information):**
 - OS 4.1
 - AAD version (`git log --pretty=oneline -2`)
2264128508fdd074b26886f701554923a9cbc492 Fix the deployment issue. (#597)
 - Ansible (`ansible --version`)
 - cloud provider CLI (aws-cli,  azure, ..)
Existing OCP 4.1

**Additional context**

**Comment by fridim** [comment]
i understand that this issue was fixed by e9b90b
Closing. Please re-open if it's not the case.
