### ISSUE TITLE
Request - Add Security Group Name Property

### ISSUE THREAD

**Issue by willtome** [redhat-cop/agnosticd#6947]
https://github.com/redhat-cop/agnosticd/blob/e7a1321e70807f039e5a800cb8131e00dd523fda/ansible/roles-infra/infra-ec2-template-generate/templates/cloud_template.j2#L78C12-L78C35

Add the GroupName Property to match the Name tag otherwise the actual name includes a random hash

**Comment by fridim** [comment]
Thank you for reporting this issue.

Can you  elaborate why having a random hash for GroupName is an issue?
