### ISSUE TITLE
Integreatly Workshop fails to provision in DEV and TEST (works on PROD)

### ISSUE THREAD

**Issue by trepel** [redhat-cop/agnosticd#731]
**Describe the bug**
This affects the Integreatly Workshop in DEV and TEST. Does not affect PROD.

Following error can be seen when provisioning Integreatly Workshop in DEV and TEST:
```
TASK [ocp-workload-integreatly : Clone integreatly installer GIT repository] ***
Tuesday 24 September 2019  12:20:19 -0400 (0:00:00.091)       0:44:33.558 *****
fatal: [master1.trepel-5d3f.internal]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ig_version' is undefined\n\nThe error appears to have been in '/tmp/ocp-workshop-trepel-5d3f/ansible_agnostic_deployer/ansible/roles/ocp-workload-integreatly/tasks/pre_workload.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Clone integreatly installer GIT repository\n  ^ here\n"}
```

It seems `ig_version` is not propagated correctly. Recently, the dropdown selector has been introduced so that the user can specify what version of Integreatly Workshop they can use. Their selection is then stored in this `ig_version`. I can only guess but I assume the piece of code has only been applied to PROD, but not to DEV and TEST.

**To Reproduce**

1. Provision Integreatly Workshop in DEV or TEST

**Expected behavior**
Integreatly Workshop should be provisioned successfully as when using PROD

**Screenshots / logs**
See above for log snippet. For full log see `test-ocp-workshop-trepel-5d3f.log` in a standard TEST log location.

**Verions (please complete the following information):**
Sorry, not sure about these, probably not relevant anyway.

**Additional context**
None

**Comment by trepel** [comment]
Hello, any update on this? It would force us to push untested release to PROD and do the testing there which is not optimal.

**Comment by trepel** [comment]
We are releasing a patch release shortly - that is not that risky but late this year/early next year we will be releasing a minor version of Integreatly and it would be good to be able to test on DEV/TEST by then.

**Comment by fridim** [comment]
That looks like an issue with variables with the catalog item in Cloudforms (or the Dialog) more than with integreatly or agnosticd.

We can also specify a version in the vars in agnosticv GPTE private repo for the TEST/DEV catalog items.

On the agnosticd side, maybe you can add a default value for ig_version in the workload `defaults/main.yml` ?


Closing as it's not agnosticd related.
