### ISSUE TITLE
No credentials emailed when student_name is taken from CF Params

### ISSUE THREAD

**Issue by newgoliath** [redhat-cop/agnosticd#830]
**Describe the bug**
No credentials emailed when student_name is taken from CF Params.  Should send params even when student_name was taken from CF.

**To Reproduce**
1. deploy with student_name and student_password both empty in AgnosticV: 
2. email returned with NO login information

**Expected behavior**
Expect to use the CF param student_name and generate a password and return the password via email.

**Screenshots / logs**
If applicable, add logs to help explain your problem.

**Verions (please complete the following information):**
 ```
$ git log --pretty=oneline -2                                                                        │[jmaltin-redhat.com@admin-dev (DEV) OCP4_CONFIGURATION_LAB]$ ls
d356903628b5840bfe1b6bf59c07beb373d2bd88 (HEAD -> development, tag: ocp4-migration-prod-0.4, tag: ocp4-migration-prod-0.3, origin/development, orig│common.yaml  dev.yaml  prod.yaml
in/HEAD) fix broken copy, remove unnecessary ssh keys (#824)                                                                                       │[jmaltin-redhat.com@admin-dev (DEV) OCP4_CONFIGURATION_LAB]$ vim *
24c3491eb10d20fd3e4ec66df92dc05bf5905ee9 Mig prod bugs (#822)                                                                                      │
```

**Comment by wkulhanek** [comment]
Not a bug in agnosticd. Needs the right email form in CF to pick up user.info

**Comment by newgoliath** [comment]
Needs to be document.
