### ISSUE TITLE
Consider Using Galaxy Collections for Workloads

### ISSUE THREAD

**Issue by djeremiah** [redhat-cop/agnosticd#919]
Right now, it is difficult to navigate the existing *-workload-* roles. There is no indexing, naming convention, or tagging to make finding a particular workload easy, or to make duplicate detection and organization possible. Some roles seem to be meant to be used together, while others are stand-alone.

Consider using the Ansible Galaxy [Collections](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html) as a packaging format for Workloads (and maybe even Configs). The format allows for standardized documentation, tagging, and distribution. It may also help to break them out into separate repos, or to allow a two tier "blessed" and "extras" approach.

This may also allow for distribution through [galaxy.ansible.com](galaxy.ansible.com), a local Galaxy install or Red Hat Automation Hub in the future.

**Comment by fridim** [comment]
we recently introduced the ability to pull collections.

https://github.com/redhat-cop/agnosticd/blob/development/ansible/install_galaxy_roles.yml#L37-L46

It's a new feature in agnosticd, so we don't have a lot of experience with it, but as soon as we have more usecases we will document and add examples and guidelines.
